Fixed minor bugs, re-factored code to make it more readable.

diff --git a/lpassh-add b/lpassh-add
--- a/lpassh-add
+++ b/lpassh-add
@@ -208,17 +208,18 @@ export LPASS_AGENT_DISABLE LPASS_DISABLE_PINENTRY \
 # ===========
 
 if [ -z "${__LPASSH_ADD_TTY-}" ]; then
-
-    # Secure the environment
-    # ----------------------
+    # Set a secure path.
     PATH=/bin:/usr/bin:/usr/local/bin
     # shellcheck disable=2006
     PATH="$PATH:"`getconf PATH`
+
+    # Make sure not fancy input field separator is set.
     unset IFS
-    export PATH IFS PWD
+
+    # Make sure the temporary directory is set.
     : "${TMPDIR:=${HOME:?}}"
 
-    __LPASSH_ADD_ASKPASS=''
+    # Make sure SSH_ASKPASS points to system programme.
     if [ "${SSH_ASKPASS-}" ]; then
         # shellcheck disable=2006,2046
         if [ "$SSH_ASKPASS" = `basename "$SSH_ASKPASS"` ]; then
@@ -246,11 +247,10 @@ if [ -z "${__LPASSH_ADD_TTY-}" ]; then
             ) || panic $? '%s: insecure.' "$SSH_ASKPASS"
             __LPASSH_ADD_ASKPASS="$SSH_ASKPASS"
         fi
-        export __LPASSH_ADD_ASKPASS
     fi
+    export PATH IFS PWD __LPASSH_ADD_ASKPASS
 
     # Parse arguments
-    # ---------------
     if [ $# -gt 0 ]; then
         for ARG
         do
@@ -280,8 +280,7 @@ EOF
         done
     fi
 
-    # Prepare temporary directory
-    # ---------------------------
+    # Prepare temporary directory.
     register_onexit "$@"
     readonly LPASSH_ADD_TMP="${TMPDIR%/}/lpassh-add"
     export LPASSH_ADD_TMP
@@ -289,16 +288,17 @@ EOF
     mkdir -m 0700 "$LPASSH_ADD_TMP" || exit 69
     export TMPDIR="$LPASSH_ADD_TMP"
 
-    # Log into LastPass
-    # -----------------
+    # Check if a we're logged into LastPass *or* a username has been given.
     lpass status --quiet || [ "${LPASSH_ADD_USERNAME-}" ] || \
         panic 69 'not logged into LastPass.'
 
+    # Check what TTY to read passwords from.
     # shellcheck disable=2006
     __LPASSH_ADD_TTY=`tty` || :
     [ "$__LPASSH_ADD_TTY" ] || panic 69 'could not get TTY.'
     export __LPASSH_ADD_TTY
 
+    # Call ssh-add.
     case $# in
         0) SSH_ASKPASS="$0" DISPLAY='' LC_ALL=C ssh-add "$@" ;;
         *) SSH_ASKPASS="$0" DISPLAY='' LC_ALL=C ssh-add ;;
@@ -306,17 +306,27 @@ EOF
     exit
 fi
 
-PROMPT="$*" PASSWORD='' LPASS_PROMT='LastPass master password: '
+
+# MAIN
+# ====
+
+# Check which key `ssh-add` tries to unlock.
+PROMPT="$*"
 # shellcheck disable=2006
 PRIVKEY_NEEDLE_FILE=`regex 's/^[^\/]\{1,\}//; s/: $//' "$PROMPT"`
+
+# Check whether we should unlock that key.
 IFS=:
-[ "${LPASSH_ADD_KEYS-}" ] && \
-    { contains "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_KEYS" || exit 1; }
-[ "${LPASSH_ADD_IGNORE_KEYS-}" ] &&
-    contains "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_IGNORE_KEYS" && exit 1
+if [ "${LPASSH_ADD_KEYS-}" ]; then
+    contains "$PRIVKEY_NEEDLE_FILE" "${LPASSH_ADD_KEYS-}"    || exit 1
+fi
+contains "$PRIVKEY_NEEDLE_FILE" "${LPASSH_ADD_IGNORE_KEYS-}" && exit 1
 unset IFS
+
+# Ask for LastPass password.
+LPASS_PROMT='LastPass master password: '
 if [ "${__LPASSH_ADD_ASKPASS-}" ]; then
-    warn 'askpass PID: %d.' "$$"
+    warn 'ID of process asking for passphrase: %d.' "$$"
     # shellcheck disable=2006
     PASSWORD=`"$__LPASSH_ADD_ASKPASS" "$LPASS_PROMT"`
 else
@@ -325,8 +335,10 @@ else
     # shellcheck disable=2006
     PASSWORD=`askpass "$LPASS_PROMT" <"$__LPASSH_ADD_TTY"`
 fi
+[ "${PASSWORD-}" ] || panic 64 'no password, aborting.'
 readonly PASSWORD
-[ "$PASSWORD" ] || panic 64 'no password, aborting.'
+
+# Log into LastPass if necessary.
 lpass status --quiet || {
     register_onexit
     auth_lpass "$PASSWORD" login --color=never "$LPASSH_ADD_USERNAME" \
@@ -334,8 +346,12 @@ lpass status --quiet || {
     # shellcheck disable=2016
     EX='auth_lpass "$PASSWORD" logout --force 2>/dev/null 1>&2'
 }
-read -r PUBKEY_NEEDLE <"$PRIVKEY_NEEDLE_FILE.pub" || \
-    { [ "$?" -gt 1 ] && exit 66; }
+
+# Read the public key file.
+read -r PUBKEY_NEEDLE <"$PRIVKEY_NEEDLE_FILE.pub" || ERR=$?
+[ ${ERR-0} -gt 1 ] && exit 66
+
+# Lookup the LastPass IDs of *all* SSh keys, caching the result.
 {
     KEY_IDS="$LPASSH_ADD_TMP/key_ids"
     cat "$KEY_IDS" 2>/dev/null || {
@@ -343,30 +359,24 @@ read -r PUBKEY_NEEDLE <"$PRIVKEY_NEEDLE_FILE.pub" || \
         sed -n 's/.*\[id: \([[:digit:]]\{1,\}\)\]/\1/p'         |
         tee "$KEY_IDS" 2>/dev/null || :
     }
-} | {
-    while read -r ID; do
-        PUBKEY_STRAW_FILE="$LPASSH_ADD_TMP/$ID"
-        read -r PUBKEY_STRAW 2>/dev/null <"$PUBKEY_STRAW_FILE" || {
-            # shellcheck disable=2006
-            PUBKEY_STRAW=`auth_lpass "$PASSWORD" show \
-                --field='Public Key' "$ID"`
-            [ "$PUBKEY_STRAW" ] || continue
-            [ -d "$LPASSH_ADD_TMP" ] && cat <<EOF >"$PUBKEY_STRAW_FILE"
-$PUBKEY_STRAW
-EOF
-        }
-        if [ "$PUBKEY_STRAW" = "$PUBKEY_NEEDLE" ]; then
-                auth_lpass "$PASSWORD" show --field=Passphrase "$ID"
-                exit
-        fi
-    done
-    echo "$PRIVKEY_NEEDLE_FILE not found in LastPass." >&2
-    if [ "${__LPASSH_ADD_ASKPASS-}" ]; then
-        "$__LPASSH_ADD_ASKPASS" "$PROMPT"
-    else
-        [ "$__LPASSH_ADD_TTY" != "not a tty" ] && \
-        [ -c "$__LPASSH_ADD_TTY" ] || \
-            panic 64 "no tty, can't ask for passphrase."
-        askpass "$PROMPT" <"$__LPASSH_ADD_TTY"
+} | 
+
+# Search the given key by its public key and print the passphrase to STDOUT.
+while read -r ID; do
+    # shellcheck disable=2006
+    PUBKEY_STRAW=`auth_lpass "$PASSWORD" show --field='Public Key' "$ID"`
+    if [ "$PUBKEY_STRAW" ] && [ "$PUBKEY_STRAW" = "$PUBKEY_NEEDLE" ]; then
+        auth_lpass "$PASSWORD" show --field=Passphrase "$ID"
+        exit
     fi
-}
+done && exit
+
+# If we reach this point, then we couldn't find the key.
+warn  '%s: not found in LastPass.' "$PRIVKEY_NEEDLE_FILE"
+if [ "${__LPASSH_ADD_ASKPASS-}" ]; then
+    "$__LPASSH_ADD_ASKPASS" "$PROMPT"
+elif [ "$__LPASSH_ADD_TTY" != "not a tty" ] && [ -c "$__LPASSH_ADD_TTY" ]; then
+    askpass "$PROMPT" <"$__LPASSH_ADD_TTY"
+else
+    panic 64 "no tty, can't ask for passphrase."
+fi
