Removed superfluous behaviour, minor re-factoring.

diff --git a/lpassh-add b/lpassh-add
--- a/lpassh-add
+++ b/lpassh-add
@@ -1,7 +1,7 @@
 #!/bin/sh
-# lpass-ssh-add v1.0.2 - Get SSh private key passphrases from LastPass
+# lpass-ssh-add v1.0.3 - Get SSh private key passphrases from LastPass
 #
-# Copyright 2018 Odin Kroeger
+# Copyright 2018, 2019 Odin Kroeger
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -24,13 +24,15 @@
 # See <https://github.com/okroeger/lpassh-add/> for more information.
 #
 #
-# Remarks on Portability
-# ======================
+# Portability
+# ===========
 #
-# In order of appearance:
+# This script complies with the Shell Command Language as POSIX specifies it.
+# However, it also aims to be SVR4 compatible and to work with buggy shells.
+# This requires some weird constructs; in order of appearance:
 #
 # onexit():
-# * I do not use ``unset``, because some shells abort when
+# * I do not use `unset`, because some shells abort when
 #   a variable that hasn't been set is unset.
 #
 # onexit(), main script:
@@ -50,7 +52,7 @@
 #
 # regex():
 # * I use:
-#       foo=`sed 'regex' <<EOF
+#       foo=`sed 'pattern' <<EOF
 #       $bar
 #       EOF`
 #
@@ -69,9 +71,9 @@
 #   Or:
 #       printf -- '%s\n' "$var"
 #
-#   Neither ``echo`` nor ``printf`` are safe with arbitrary input.
-#   Also, in some shells ``echo`` and ``printf`` are not builtins, to the
-#   effect that they, and "$var", would show up in the output of ``ps``.
+#   Neither `echo` nor `printf` are safe with arbitrary input.
+#   Also, in some shells `echo` and `printf` are not builtins, to the
+#   effect that they, and "$var", would show up in the output of `ps`.
 #   This would allow any user on a system to snoop passwords.
 #
 # * I use:
@@ -80,34 +82,20 @@
 #   Instead of:
 #       $(...)
 #
-# * I sometimes call ``register_onexit`` with arguments, even though it doesn't
-#   take any, because, in old shells, ``$@`` and ``$*`` are *not* reset to the
+# * I sometimes call `register_onexit` with arguments, even though it doesn't
+#   take any, because, in old shells, `$@` and `$*` are *not* reset to the
 #   arguments of the caller upon return. That is, they always contain the
 #   arguments to the last function call, regardless of context or scope.
 #
-# * I test whether any arguments have been passed before referencing ``$@``
-#   because some shells, when ``set -u`` is in effect, will abort if ``$@``
-#   is referenced but no arguments have been passed.
-
-[ "$BASH_VERSION" ] && set -o posix
-[ "$ZSH_VERSION" ] && emulate sh 2>/dev/null
-# shellcheck disable=2034
-BIN_SH=xpg4 NULLCMD=:
-export BIN_SH
-
-set -Cefu
-umask 077
-
-: "${LPASSH_ADD_LASTPASS_FOLDER:=SSh keys}"
-[ "${LPASS_AGENT_DISABLE-0}" -eq 1 ] || LPASS_AGENT_DISABLE=1
-[ "${LPASS_DISABLE_PINENTRY-0}" -eq 1 ] || LPASS_DISABLE_PINENTRY=1
-[ "${LPASS_AGENT_PINENTRY-}" ] && LPASS_PINENTRY=''
-LPASS_AUTO_SYNC_TIME=30
-export LPASS_AGENT_DISABLE LPASS_DISABLE_PINENTRY \
-    LPASS_PINENTRY LPASS_AUTO_SYNC_TIME
+# * I test whether any arguments have been passed before referencing `$@`
+#   because some shells will abort if `$@` is referenced but no arguments
+#   have and `set -u` is in effect.
 
 
-# Takes a signal as argument, runs $EX, propagates the signal, and exits.
+# Functions
+# =========
+
+# Takes a SIGNAL as argument, runs `$EX`, propagates the signal, and exits.
 onexit() {
     __ONEXIT_STATUS=$?
     trap '' 0 "${1:?'onexit: missing SIGNAL.'}" || :
@@ -118,7 +106,7 @@ onexit() {
     exit "$__ONEXIT_STATUS"
 }
 
-# Registers onexit to catch signals 0, 1, 2, 3, 6, and 15.
+# Registers `onexit` to catch signals 0, 1, 2, 3, 6, and 15.
 # shellcheck disable=2064
 register_onexit() {
     for __REGISTER_ONEXIT_SIGNO in 0 1 2 3 6 13 15
@@ -127,17 +115,39 @@ register_onexit() {
     done
 }
 
-# Takes an exit STATUS, a FORMAT, and arguments as arguments,
+# Takes a MESSAGE and ARGUMENTS (think `printf`) and
+# prints the formated MESSAGE to STDERR.
+warn() (
+    msg="${1:?'warn: missing MESSAGE.'}"
+    shift
+    # shellcheck disable=2059
+    printf -- "lpassh-add: $msg\\n" "$@" >&2
+)
+
+# Takes an exit STATUS, a MESSAGE, and ARGUMENTS,
 # prints the MESSAGE to STDERR and exits with STATUS.
 # shellcheck disable=2059
 panic() {
-    set +eu
-    __PANIC_STATUS="${1:?'panic: missing STATUS.'}"
-    __PANIC_FORMAT="${2:?'panic: missing FORMAT.'}"
-    shift 2
-    printf "lpassh-add: $__PANIC_FORMAT\\n" "$@" >&2
-    exit "$__PANIC_STATUS"
+    (
+        set +eu
+        status="${1:?'panic: missing STATUS.'}"
+        shift
+        warn "$@"
+        exit "$status"
+    )
+    exit
 }
+
+# Takes a NEEDLE and a HAYSTACK as arguments,
+# returns true if NEEDLE is in HAYSTACK.
+contains() (
+    needle="${1:?'contains: missing NEEDLE.'}"
+    shift
+    for straw
+    do [ "$needle" = "$straw" ] && return
+    done
+    return 1
+)
 
 # Takes a REGEX and a STRING as arguments,
 # applies REGEX to STRING, and prints the result.
@@ -146,16 +156,6 @@ regex() {
 $2
 EOF
 }
-
-# Takes a NEEDLE and a HAYSTACK as arguments,
-# returns true if NEEDLE is in HAYSTACK.
-inlist() (
-    needle="${1:?'inlist: missing NEEDLE.'}"; shift
-    for straw
-    do [ "$needle" = "$straw" ] && return
-    done
-    return 1
-)
 
 # Takes a prompt as argument and asks for a password.
 # shellcheck disable=2006
@@ -175,8 +175,8 @@ $pass
 EOF
 )
 
-# Takes a PASSWORD and ARGUMENTS for ``lpass``
-# and runs ``lpass`` with ARGUMENTS, authenticating with PASSWORD.
+# Takes a PASSWORD and ARGUMENTS for `lpass` and
+# runs `lpass` with ARGUMENTS, authenticating with PASSWORD.
 auth_lpass() (
     password="${1:?'auth_lpass: missing PASSWORD.'}"; shift
     exec lpass "$@" <<EOF
@@ -184,12 +184,42 @@ $password
 EOF
 )
 
-if ! [ "${__LPASSH_ADD_TTY-}" ]; then
-    # shellcheck disable=2006
+
+# Init
+# ====
+
+# shellcheck disable=2039
+[ "$BASH_VERSION" ] && set -o posix
+[ "$ZSH_VERSION" ] && emulate sh 2>/dev/null
+# shellcheck disable=2034
+BIN_SH=xpg4 NULLCMD=:
+export BIN_SH
+
+set -Cefu
+umask 077
+
+: "${LPASSH_ADD_LASTPASS_FOLDER:=SSh keys}"
+[ "${LPASS_AGENT_DISABLE-0}" -eq 1 ] || LPASS_AGENT_DISABLE=1
+[ "${LPASS_DISABLE_PINENTRY-0}" -eq 1 ] || LPASS_DISABLE_PINENTRY=1
+[ "${LPASS_AGENT_PINENTRY-}" ] && LPASS_PINENTRY=''
+LPASS_AUTO_SYNC_TIME=30
+export LPASS_AGENT_DISABLE LPASS_DISABLE_PINENTRY \
+    LPASS_PINENTRY LPASS_AUTO_SYNC_TIME
+
+
+# Main
+# ====
+
+[ "${__LPASSH_ADD_TTY-}" ] || {
     PATH=/bin:/usr/bin:/usr/local/bin
+    # shellcheck disable=2006
     PATH="$PATH:"`getconf PATH`
     unset IFS
-    export PATH IFS
+    # `$PWD` is where the shell thinks you are, not where you are.
+    cd -P . || exit 69
+    # shellcheck disable=2006
+    PWD=`pwd`
+    export PATH IFS PWD
     : "${TMPDIR:=${HOME:?}}"
     if [ $# -gt 0 ]; then
         for ARG
@@ -228,31 +258,11 @@ EOF
     mkdir -m 0700 "$LPASSH_ADD_TMP" || exit 69
     export TMPDIR="$LPASSH_ADD_TMP"
     mkdir -m 0700 "$TMPDIR/lpass" || exit 69
-    if ! [ "${LPASS_HOME-}" ]; then
-        if [ "${XDG_RUNTIME_DIR-}" ]; then
-            for DIR in \
-                "${XDG_CONFIG_HOME-}" "${XDG_DATA_HOME-}" "$XDG_RUNTIME_DIR"
-            do
-                # shellcheck disable=2015
-                [ "$DIR" ] && [ -d "$DIR/lpass" ] || continue
-                LPASS_HOME="${DIR%/}/lpass"
-                break
-            done
-        fi
-        ! [ "${LPASS_HOME-}" ] && [ -d "${HOME:?}/.lpass" ] && \
-            LPASS_HOME="$HOME/.lpass"
-    fi
-    [ -d "$LPASS_HOME" ] || [ -s "$LPASS_HOME" ] && \
-        { set +f; cp -a "$LPASS_HOME/"* "$TMPDIR/lpass"; set -f; }
-    rm -f "$TMPDIR/lpass/env" || exit 69
-    HOME="$TMPDIR" LPASS_HOME="$TMPDIR/lpass" XDG_RUNTIME_DIR="$TMPDIR" \
-        XDG_CONFIG_HOME="$TMPDIR" XDG_DATA_HOME="$TMPDIR"
-    export HOME LPASS_HOME XDG_RUNTIME_DIR XDG_CONFIG_HOME XDG_DATA_HOME
     lpass status --quiet || [ "${LPASSH_ADD_USERNAME-}" ] || \
         panic 69 'not logged into LastPass.'
     # shellcheck disable=2006
     __LPASSH_ADD_TTY=`tty` || :
-    [ "$__LPASSH_ADD_TTY" ] || panic 69 'cannot determine tty.'
+    [ "$__LPASSH_ADD_TTY" ] || panic 69 'could not get TTY.'
     export __LPASSH_ADD_TTY
     __LPASSH_ADD_ASKPASS=''
     if [ "${SSH_ASKPASS-}" ]; then
@@ -266,7 +276,7 @@ EOF
                     unset IFS
                     [ "$i" ] || continue
                     path="${path-}/$i"
-                    # shellcheck disable=2006,2046
+                    # shellcheck disable=2006,2012
                     set -- `ls -l -d "${path:?}" | awk '{print $1, $3, $4}'`
                     [ $# -eq 3 ] || panic 79 '%s: cannot parse.' "$path"
                     case ${????%1} in
@@ -275,78 +285,82 @@ EOF
                     [ "$2" = root ] || \
                         panic 69 '%s: not owned by root.' "$path"
                     case $3 in root|admin|wheel) continue;; esac
-                    panic 69 '%s: owned by non-privileged group.' "$path"
+                    panic 69 '%s: not owned by system group.' "$path"
                 done
                 exit 0
-            ) || panic $? '%s: not safe.' "$SSH_ASKPASS"
+            ) || panic $? '%s: not secure.' "$SSH_ASKPASS"
             __LPASSH_ADD_ASKPASS="$SSH_ASKPASS"
         fi
         export __LPASSH_ADD_ASKPASS
     fi
     case $# in
-        0) SSH_ASKPASS="$0" DISPLAY='' LC_ALL=C ssh-add "$@" ;;
-        *) SSH_ASKPASS="$0" DISPLAY='' LC_ALL=C ssh-add ;;
+        0) SSH_ASKPASS="$PWD/$0" DISPLAY='' LC_ALL=C ssh-add "$@" ;;
+        *) SSH_ASKPASS="$PWD/$0" DISPLAY='' LC_ALL=C ssh-add ;;
     esac </dev/null
-else
-    PROMPT="$*" PASSWORD='' LPASS_PROMT='LastPass master password: '
+    exit
+}
+
+PROMPT="$*" PASSWORD='' LPASS_PROMT='LastPass master password: '
+# shellcheck disable=2006
+PRIVKEY_NEEDLE_FILE=`regex 's/^[^\/]\{1,\}//; s/: $//' "$PROMPT"`
+IFS=:
+[ "${LPASSH_ADD_KEYS-}" ] && \
+    { contains "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_KEYS" || exit 1; }
+[ "${LPASSH_ADD_IGNORE_KEYS-}" ] &&
+    contains "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_IGNORE_KEYS" && exit 1
+unset IFS
+if [ "${__LPASSH_ADD_ASKPASS-}" ]; then
+    warn 'PID: %d.' "$$"
     # shellcheck disable=2006
-    PRIVKEY_NEEDLE_FILE=`regex 's/^[^\/]\{1,\}//; s/: $//' "$PROMPT"`
-    IFS=:
-    [ "${LPASSH_ADD_KEYS-}" ] && \
-        { inlist "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_KEYS" || exit 1; }
-    [ "${LPASSH_ADD_IGNORE_KEYS-}" ] &&
-        inlist "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_IGNORE_KEYS" && exit 1
-    unset IFS
-    if [ "${__LPASSH_ADD_ASKPASS-}" ]; then
-        PASSWORD=`"$__LPASSH_ADD_ASKPASS" "$LPASS_PROMT"`
-    else
-        [ "$__LPASSH_ADD_TTY" != "not a tty" ] && [ -c "$__LPASSH_ADD_TTY" ] \
-            || panic 64 "no tty, can't ask for LastPass master password."
-        PASSWORD=`askpass "$LPASS_PROMT" <"$__LPASSH_ADD_TTY"`
-    fi
-    readonly PASSWORD
-    [ "$PASSWORD" ] || panic 64 'no password, aborting.'
-    lpass status --quiet || {
-        register_onexit
-        auth_lpass "$PASSWORD" login --color=never "$LPASSH_ADD_USERNAME" \
-            2>/dev/null 1>&2 || panic 69 'login to LastPass failed.'
-        # shellcheck disable=2016
-        EX='auth_lpass "$PASSWORD" logout --force 2>/dev/null 1>&2'
+    PASSWORD=`"$__LPASSH_ADD_ASKPASS" "$LPASS_PROMT"`
+else
+    [ "$__LPASSH_ADD_TTY" != "not a tty" ] && [ -c "$__LPASSH_ADD_TTY" ] \
+        || panic 64 "no tty, can't ask for LastPass master password."
+    # shellcheck disable=2006
+    PASSWORD=`askpass "$LPASS_PROMT" <"$__LPASSH_ADD_TTY"`
+fi
+readonly PASSWORD
+[ "$PASSWORD" ] || panic 64 'no password, aborting.'
+lpass status --quiet || {
+    register_onexit
+    auth_lpass "$PASSWORD" login --color=never "$LPASSH_ADD_USERNAME" \
+        2>/dev/null 1>&2 || panic 69 'login to LastPass failed.'
+    # shellcheck disable=2016
+    EX='auth_lpass "$PASSWORD" logout --force 2>/dev/null 1>&2'
+}
+read -r PUBKEY_NEEDLE <"$PRIVKEY_NEEDLE_FILE.pub" || \
+    { [ "$?" -gt 1 ] && exit 66; }
+{
+    KEY_IDS="$LPASSH_ADD_TMP/key_ids"
+    cat "$KEY_IDS" 2>/dev/null || {
+        auth_lpass "$PASSWORD" ls "$LPASSH_ADD_LASTPASS_FOLDER" |
+        sed -n 's/.*\[id: \([[:digit:]]\{1,\}\)\]/\1/p'         |
+        tee "$KEY_IDS" 2>/dev/null || :
     }
-    read -r PUBKEY_NEEDLE <"$PRIVKEY_NEEDLE_FILE.pub" || \
-        { [ "$?" -gt 1 ] && exit 66; }
-    {
-        KEY_IDS="$LPASSH_ADD_TMP/key_ids"
-        cat "$KEY_IDS" 2>/dev/null || {
-            auth_lpass "$PASSWORD" ls "$LPASSH_ADD_LASTPASS_FOLDER" |
-            sed -n 's/.*\[id: \([[:digit:]]\{1,\}\)\]/\1/p'         |
-            tee "$KEY_IDS" 2>/dev/null || :
-        }
-    } | {
-        while read -r ID; do
-            PUBKEY_STRAW_FILE="$LPASSH_ADD_TMP/$ID"
-            read -r PUBKEY_STRAW 2>/dev/null <"$PUBKEY_STRAW_FILE" || {
-                # shellcheck disable=2006
-                PUBKEY_STRAW=`auth_lpass "$PASSWORD" show \
-                    --field='Public Key' "$ID"`
-                [ "$PUBKEY_STRAW" ] || continue
-                [ -d "$LPASSH_ADD_TMP" ] && cat <<EOF >"$PUBKEY_STRAW_FILE"
+} | {
+    while read -r ID; do
+        PUBKEY_STRAW_FILE="$LPASSH_ADD_TMP/$ID"
+        read -r PUBKEY_STRAW 2>/dev/null <"$PUBKEY_STRAW_FILE" || {
+            # shellcheck disable=2006
+            PUBKEY_STRAW=`auth_lpass "$PASSWORD" show \
+                --field='Public Key' "$ID"`
+            [ "$PUBKEY_STRAW" ] || continue
+            [ -d "$LPASSH_ADD_TMP" ] && cat <<EOF >"$PUBKEY_STRAW_FILE"
 $PUBKEY_STRAW
 EOF
-            }
-            if [ "$PUBKEY_STRAW" = "$PUBKEY_NEEDLE" ]; then
-                  auth_lpass "$PASSWORD" show --field=Passphrase "$ID"
-                  exit
-            fi
-        done
-        echo "$PRIVKEY_NEEDLE_FILE not found in LastPass." >&2
-        if [ "${__LPASSH_ADD_ASKPASS-}" ]; then
-            "$__LPASSH_ADD_ASKPASS" "$PROMPT"
-        else
-            [ "$__LPASSH_ADD_TTY" != "not a tty" ] && \
-            [ -c "$__LPASSH_ADD_TTY" ] || \
-                panic 64 "no tty, can't ask for passphrase."
-            askpass "$PROMPT" <"$__LPASSH_ADD_TTY"
+        }
+        if [ "$PUBKEY_STRAW" = "$PUBKEY_NEEDLE" ]; then
+                auth_lpass "$PASSWORD" show --field=Passphrase "$ID"
+                exit
         fi
-    }
-fi
+    done
+    echo "$PRIVKEY_NEEDLE_FILE not found in LastPass." >&2
+    if [ "${__LPASSH_ADD_ASKPASS-}" ]; then
+        "$__LPASSH_ADD_ASKPASS" "$PROMPT"
+    else
+        [ "$__LPASSH_ADD_TTY" != "not a tty" ] && \
+        [ -c "$__LPASSH_ADD_TTY" ] || \
+            panic 64 "no tty, can't ask for passphrase."
+        askpass "$PROMPT" <"$__LPASSH_ADD_TTY"
+    fi
+}
