Re-arranged logic.

diff --git a/lpassh-add b/lpassh-add
--- a/lpassh-add
+++ b/lpassh-add
@@ -184,73 +184,46 @@ $password
 EOF
 )
 
-if [ "${__LPASSH_ADD_TTY-}" ]; then
-    PROMPT="$*" PASSWORD='' LPASS_PROMT='LastPass master password: '
-    # shellcheck disable=2006
-    PRIVKEY_NEEDLE_FILE=`regex 's/^[^\/]\{1,\}//; s/: $//' "$PROMPT"`
-    IFS=:
-    [ "${LPASSH_ADD_KEYS-}" ] && \
-        { inlist "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_KEYS" || exit 1; }
-    [ "${LPASSH_ADD_IGNORE_KEYS-}" ] &&
-        inlist "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_IGNORE_KEYS" && exit 1
-    unset IFS
-    [ "$__LPASSH_ADD_TTY" != "not a tty" ] && [ -c "$__LPASSH_ADD_TTY" ] || \
-        panic 64 "no tty, can't ask for LastPass master password."
-    if [ "${__LPASSH_ADD_ASKPASS-}" ]
-        then PASSWORD=$("$__LPASSH_ADD_ASKPASS" $LPASS_PROMT)
-        else PASSWORD=$(askpass $LPASS_PROMT <"$__LPASSH_ADD_TTY")
-    fi
-    readonly PASSWORD
-    [ "$PASSWORD" ] || panic 64 'no password, aborting.'
-    lpass status --quiet || {
-        register_onexit
-        auth_lpass "$PASSWORD" login --color=never "$LPASSH_ADD_USERNAME" \
-            2>/dev/null 1>&2 || panic 69 'login to LastPass failed.'
-        # shellcheck disable=2016
-        EX='auth_lpass "$PASSWORD" logout --force 2>/dev/null 1>&2'
-    }
-    read -r PUBKEY_NEEDLE <"$PRIVKEY_NEEDLE_FILE.pub" || \
-        { [ "$?" -gt 1 ] && exit 66; }
-    {
-        KEY_IDS="$LPASSH_ADD_TMP/key_ids"
-        cat "$KEY_IDS" 2>/dev/null || {
-            auth_lpass "$PASSWORD" ls "$LPASSH_ADD_LASTPASS_FOLDER" |
-            sed -n 's/.*\[id: \([[:digit:]]\{1,\}\)\]/\1/p'         |
-            tee "$KEY_IDS" 2>/dev/null || :
-        }
-    } | {
-        while read -r ID; do
-            PUBKEY_STRAW_FILE="$LPASSH_ADD_TMP/$ID"
-            read -r PUBKEY_STRAW 2>/dev/null <"$PUBKEY_STRAW_FILE" || {
-                # shellcheck disable=2006
-                PUBKEY_STRAW=`auth_lpass "$PASSWORD" show \
-                    --field='Public Key' "$ID"`
-                [ "$PUBKEY_STRAW" ] || continue
-                [ -d "$LPASSH_ADD_TMP" ] && cat <<EOF >"$PUBKEY_STRAW_FILE"
-$PUBKEY_STRAW
-EOF
-            }
-            if [ "$PUBKEY_STRAW" = "$PUBKEY_NEEDLE" ]; then
-                  auth_lpass "$PASSWORD" show --field=Passphrase "$ID"
-                  exit
-            fi
-        done
-        echo "$PRIVKEY_NEEDLE_FILE not found in LastPass." >&2
-        if [ "${__LPASSH_ADD_ASKPASS-}" ]
-            then "$__LPASSH_ADD_ASKPASS" "$PROMPT"
-            else askpass "$PROMPT" <"$__LPASSH_ADD_TTY"
-        fi
-    }
-else
+if ! [ "${__LPASSH_ADD_TTY-}" ]; then
     # shellcheck disable=2006
     PATH=/bin:/usr/bin:/usr/local/bin
     PATH="$PATH:"`getconf PATH`
     unset IFS
     export PATH IFS
     : "${TMPDIR:=${HOME:?}}"
+    if [ $# -gt 0 ]; then
+        for ARG
+        do
+            case $ARG in
+                -h|--help)
+                    cat <<EOF
+usage: lpassh-add [options] [file ...]
+lpassh-add accepts the same arguments as ssh-add.
+EOF
+                    exit
+                    ;;
+                --version)
+                    cat <<EOF
+lpassh-add v1.0.0
+(c) 2018 Odin Kroeger
+EOF
+                    exit
+                    ;;
+                --)
+                    break
+                    ;;
+                -*)
+                    :
+                    ;;
+                *)
+                    break
+                    ;;
+            esac
+        done
+    fi
+    register_onexit "$@"
     readonly LPASSH_ADD_TMP="${TMPDIR%/}/lpassh-add"
     export LPASSH_ADD_TMP
-    register_onexit "$@"
     EX="[ -d \"\$LPASSH_ADD_TMP\" ] && rm -rf \"\$LPASSH_ADD_TMP\""
     mkdir -m 0700 "$LPASSH_ADD_TMP" || exit 69
     export TMPDIR="$LPASSH_ADD_TMP"
@@ -308,37 +281,65 @@ else
         fi
     fi
     case $# in
-        0) SSH_ASKPASS="$0" DISPLAY='' LC_ALL=C ssh-add ;;
-        *)
-            for ARG
-            do
-                case $ARG in
-                    -h|--help)
-                        cat <<EOF
-usage: lpassh-add [options] [file ...]
-lpassh-add accepts the same arguments as ssh-add.
-EOF
-                        exit
-                        ;;
-                    --version)
-                        cat <<EOF
-lpassh-add v1.0.0
-(c) 2018 Odin Kroeger
-EOF
-                        exit
-                        ;;
-                    --)
-                        break
-                        ;;
-                    -*)
-                        :
-                        ;;
-                    *)
-                        break
-                        ;;
-                esac
-            done
-            SSH_ASKPASS="$0" DISPLAY='' LC_ALL=C ssh-add "$@"
-            ;;
+        0) SSH_ASKPASS="$0" DISPLAY='' LC_ALL=C ssh-add "$@" ;;
+        *) SSH_ASKPASS="$0" DISPLAY='' LC_ALL=C ssh-add ;;
     esac </dev/null
+else
+    PROMPT="$*" PASSWORD='' LPASS_PROMT='LastPass master password: '
+    # shellcheck disable=2006
+    PRIVKEY_NEEDLE_FILE=`regex 's/^[^\/]\{1,\}//; s/: $//' "$PROMPT"`
+    IFS=:
+    [ "${LPASSH_ADD_KEYS-}" ] && \
+        { inlist "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_KEYS" || exit 1; }
+    [ "${LPASSH_ADD_IGNORE_KEYS-}" ] &&
+        inlist "$PRIVKEY_NEEDLE_FILE" "$LPASSH_ADD_IGNORE_KEYS" && exit 1
+    unset IFS
+    [ "$__LPASSH_ADD_TTY" != "not a tty" ] && [ -c "$__LPASSH_ADD_TTY" ] || \
+        panic 64 "no tty, can't ask for LastPass master password."
+    if [ "${__LPASSH_ADD_ASKPASS-}" ]
+        then PASSWORD=$("$__LPASSH_ADD_ASKPASS" $LPASS_PROMT)
+        else PASSWORD=$(askpass $LPASS_PROMT <"$__LPASSH_ADD_TTY")
+    fi
+    readonly PASSWORD
+    [ "$PASSWORD" ] || panic 64 'no password, aborting.'
+    lpass status --quiet || {
+        register_onexit
+        auth_lpass "$PASSWORD" login --color=never "$LPASSH_ADD_USERNAME" \
+            2>/dev/null 1>&2 || panic 69 'login to LastPass failed.'
+        # shellcheck disable=2016
+        EX='auth_lpass "$PASSWORD" logout --force 2>/dev/null 1>&2'
+    }
+    read -r PUBKEY_NEEDLE <"$PRIVKEY_NEEDLE_FILE.pub" || \
+        { [ "$?" -gt 1 ] && exit 66; }
+    {
+        KEY_IDS="$LPASSH_ADD_TMP/key_ids"
+        cat "$KEY_IDS" 2>/dev/null || {
+            auth_lpass "$PASSWORD" ls "$LPASSH_ADD_LASTPASS_FOLDER" |
+            sed -n 's/.*\[id: \([[:digit:]]\{1,\}\)\]/\1/p'         |
+            tee "$KEY_IDS" 2>/dev/null || :
+        }
+    } | {
+        while read -r ID; do
+            PUBKEY_STRAW_FILE="$LPASSH_ADD_TMP/$ID"
+            read -r PUBKEY_STRAW 2>/dev/null <"$PUBKEY_STRAW_FILE" || {
+                # shellcheck disable=2006
+                PUBKEY_STRAW=`auth_lpass "$PASSWORD" show \
+                    --field='Public Key' "$ID"`
+                [ "$PUBKEY_STRAW" ] || continue
+                [ -d "$LPASSH_ADD_TMP" ] && cat <<EOF >"$PUBKEY_STRAW_FILE"
+$PUBKEY_STRAW
+EOF
+            }
+            if [ "$PUBKEY_STRAW" = "$PUBKEY_NEEDLE" ]; then
+                  auth_lpass "$PASSWORD" show --field=Passphrase "$ID"
+                  exit
+            fi
+        done
+        echo "$PRIVKEY_NEEDLE_FILE not found in LastPass." >&2
+        if [ "${__LPASSH_ADD_ASKPASS-}" ]
+            then "$__LPASSH_ADD_ASKPASS" "$PROMPT"
+            else askpass "$PROMPT" <"$__LPASSH_ADD_TTY"
+        fi
+    }
+
 fi
